/*
 * qTest Manager API Version 8.6 - 10.2
 * qTest Manager API Version 8.6 - 10.2
 *
 * OpenAPI spec version: 8.6 - 10.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.neotys.qtest.api.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * AttachmentResource
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-01-14T16:24:25.829Z")
public class AttachmentResource {
  @SerializedName("links")
  private List<Link> links = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("content_type")
  private String contentType = null;

  @SerializedName("data")
  private String data = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("web_url")
  private String webUrl = null;

  @SerializedName("created_date")
  private OffsetDateTime createdDate = null;

  @SerializedName("author")
  private AttachmentAuthor author = null;

  @SerializedName("artifact_id")
  private Long artifactId = null;

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(value = "")
  public List<Link> getLinks() {
    return links;
  }

  public AttachmentResource name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Attachment name
   * @return name
  **/
  @ApiModelProperty(example = "Sample.docx", value = "Attachment name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AttachmentResource contentType(String contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * Attachment content type
   * @return contentType
  **/
  @ApiModelProperty(example = "application/vnd.openxmlformats-officedocument.wordprocessingml.document", value = "Attachment content type")
  public String getContentType() {
    return contentType;
  }

  public void setContentType(String contentType) {
    this.contentType = contentType;
  }

  public AttachmentResource data(String data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(example = "base64 string of Sample.docx", value = "")
  public String getData() {
    return data;
  }

  public void setData(String data) {
    this.data = data;
  }

  public AttachmentResource id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * ID of the Attachment
   * @return id
  **/
  @ApiModelProperty(example = "1", value = "ID of the Attachment")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

   /**
   * Web URL to Attachment
   * @return webUrl
  **/
  @ApiModelProperty(example = "https://apitryout.qtestnet.com/p/1/portal/attachment/testcase/attachmentId/1", value = "Web URL to Attachment")
  public String getWebUrl() {
    return webUrl;
  }

  public AttachmentResource createdDate(OffsetDateTime createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * The date Attachment was created
   * @return createdDate
  **/
  @ApiModelProperty(value = "The date Attachment was created")
  public OffsetDateTime getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(OffsetDateTime createdDate) {
    this.createdDate = createdDate;
  }

   /**
   * Who create Attachment
   * @return author
  **/
  @ApiModelProperty(value = "Who create Attachment")
  public AttachmentAuthor getAuthor() {
    return author;
  }

   /**
   * Artifact ID which Attachment linked to
   * @return artifactId
  **/
  @ApiModelProperty(example = "1", value = "Artifact ID which Attachment linked to")
  public Long getArtifactId() {
    return artifactId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttachmentResource attachmentResource = (AttachmentResource) o;
    return Objects.equals(this.links, attachmentResource.links) &&
        Objects.equals(this.name, attachmentResource.name) &&
        Objects.equals(this.contentType, attachmentResource.contentType) &&
        Objects.equals(this.data, attachmentResource.data) &&
        Objects.equals(this.id, attachmentResource.id) &&
        Objects.equals(this.webUrl, attachmentResource.webUrl) &&
        Objects.equals(this.createdDate, attachmentResource.createdDate) &&
        Objects.equals(this.author, attachmentResource.author) &&
        Objects.equals(this.artifactId, attachmentResource.artifactId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, name, contentType, data, id, webUrl, createdDate, author, artifactId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttachmentResource {\n");
    
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    webUrl: ").append(toIndentedString(webUrl)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    artifactId: ").append(toIndentedString(artifactId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

