/*
 * qTest Manager API Version 8.6 - 10.2
 * qTest Manager API Version 8.6 - 10.2
 *
 * OpenAPI spec version: 8.6 - 10.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.neotys.qtest.api.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * LdapUserVM
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-01-14T16:24:25.829Z")
public class LdapUserVM {
  @SerializedName("uid")
  private String uid = null;

  @SerializedName("firstName")
  private String firstName = null;

  @SerializedName("lastName")
  private String lastName = null;

  @SerializedName("mail")
  private String mail = null;

  @SerializedName("activationLink")
  private String activationLink = null;

  @SerializedName("mappedUserId")
  private Long mappedUserId = null;

  @SerializedName("newMappedUserName")
  private String newMappedUserName = null;

  @SerializedName("disabled")
  private Boolean disabled = false;

  public LdapUserVM uid(String uid) {
    this.uid = uid;
    return this;
  }

   /**
   * Get uid
   * @return uid
  **/
  @ApiModelProperty(value = "")
  public String getUid() {
    return uid;
  }

  public void setUid(String uid) {
    this.uid = uid;
  }

  public LdapUserVM firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public LdapUserVM lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public LdapUserVM mail(String mail) {
    this.mail = mail;
    return this;
  }

   /**
   * Get mail
   * @return mail
  **/
  @ApiModelProperty(value = "")
  public String getMail() {
    return mail;
  }

  public void setMail(String mail) {
    this.mail = mail;
  }

  public LdapUserVM activationLink(String activationLink) {
    this.activationLink = activationLink;
    return this;
  }

   /**
   * Get activationLink
   * @return activationLink
  **/
  @ApiModelProperty(value = "")
  public String getActivationLink() {
    return activationLink;
  }

  public void setActivationLink(String activationLink) {
    this.activationLink = activationLink;
  }

  public LdapUserVM mappedUserId(Long mappedUserId) {
    this.mappedUserId = mappedUserId;
    return this;
  }

   /**
   * Get mappedUserId
   * @return mappedUserId
  **/
  @ApiModelProperty(value = "")
  public Long getMappedUserId() {
    return mappedUserId;
  }

  public void setMappedUserId(Long mappedUserId) {
    this.mappedUserId = mappedUserId;
  }

  public LdapUserVM newMappedUserName(String newMappedUserName) {
    this.newMappedUserName = newMappedUserName;
    return this;
  }

   /**
   * Get newMappedUserName
   * @return newMappedUserName
  **/
  @ApiModelProperty(value = "")
  public String getNewMappedUserName() {
    return newMappedUserName;
  }

  public void setNewMappedUserName(String newMappedUserName) {
    this.newMappedUserName = newMappedUserName;
  }

  public LdapUserVM disabled(Boolean disabled) {
    this.disabled = disabled;
    return this;
  }

   /**
   * Get disabled
   * @return disabled
  **/
  @ApiModelProperty(value = "")
  public Boolean isDisabled() {
    return disabled;
  }

  public void setDisabled(Boolean disabled) {
    this.disabled = disabled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LdapUserVM ldapUserVM = (LdapUserVM) o;
    return Objects.equals(this.uid, ldapUserVM.uid) &&
        Objects.equals(this.firstName, ldapUserVM.firstName) &&
        Objects.equals(this.lastName, ldapUserVM.lastName) &&
        Objects.equals(this.mail, ldapUserVM.mail) &&
        Objects.equals(this.activationLink, ldapUserVM.activationLink) &&
        Objects.equals(this.mappedUserId, ldapUserVM.mappedUserId) &&
        Objects.equals(this.newMappedUserName, ldapUserVM.newMappedUserName) &&
        Objects.equals(this.disabled, ldapUserVM.disabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uid, firstName, lastName, mail, activationLink, mappedUserId, newMappedUserName, disabled);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LdapUserVM {\n");
    
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    mail: ").append(toIndentedString(mail)).append("\n");
    sb.append("    activationLink: ").append(toIndentedString(activationLink)).append("\n");
    sb.append("    mappedUserId: ").append(toIndentedString(mappedUserId)).append("\n");
    sb.append("    newMappedUserName: ").append(toIndentedString(newMappedUserName)).append("\n");
    sb.append("    disabled: ").append(toIndentedString(disabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

