/*
 * qTest Manager API Version 8.6 - 10.2
 * qTest Manager API Version 8.6 - 10.2
 *
 * OpenAPI spec version: 8.6 - 10.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.neotys.qtest.api.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * TokenSecretVerifierHolder
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-01-14T16:24:25.829Z")
public class TokenSecretVerifierHolder {
  @SerializedName("jiraToken")
  private String jiraToken = null;

  @SerializedName("jiraSecret")
  private String jiraSecret = null;

  @SerializedName("authorizeUrl")
  private String authorizeUrl = null;

  public TokenSecretVerifierHolder jiraToken(String jiraToken) {
    this.jiraToken = jiraToken;
    return this;
  }

   /**
   * Get jiraToken
   * @return jiraToken
  **/
  @ApiModelProperty(value = "")
  public String getJiraToken() {
    return jiraToken;
  }

  public void setJiraToken(String jiraToken) {
    this.jiraToken = jiraToken;
  }

  public TokenSecretVerifierHolder jiraSecret(String jiraSecret) {
    this.jiraSecret = jiraSecret;
    return this;
  }

   /**
   * Get jiraSecret
   * @return jiraSecret
  **/
  @ApiModelProperty(value = "")
  public String getJiraSecret() {
    return jiraSecret;
  }

  public void setJiraSecret(String jiraSecret) {
    this.jiraSecret = jiraSecret;
  }

  public TokenSecretVerifierHolder authorizeUrl(String authorizeUrl) {
    this.authorizeUrl = authorizeUrl;
    return this;
  }

   /**
   * Get authorizeUrl
   * @return authorizeUrl
  **/
  @ApiModelProperty(value = "")
  public String getAuthorizeUrl() {
    return authorizeUrl;
  }

  public void setAuthorizeUrl(String authorizeUrl) {
    this.authorizeUrl = authorizeUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TokenSecretVerifierHolder tokenSecretVerifierHolder = (TokenSecretVerifierHolder) o;
    return Objects.equals(this.jiraToken, tokenSecretVerifierHolder.jiraToken) &&
        Objects.equals(this.jiraSecret, tokenSecretVerifierHolder.jiraSecret) &&
        Objects.equals(this.authorizeUrl, tokenSecretVerifierHolder.authorizeUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jiraToken, jiraSecret, authorizeUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TokenSecretVerifierHolder {\n");
    
    sb.append("    jiraToken: ").append(toIndentedString(jiraToken)).append("\n");
    sb.append("    jiraSecret: ").append(toIndentedString(jiraSecret)).append("\n");
    sb.append("    authorizeUrl: ").append(toIndentedString(authorizeUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

