/*
 * qTest Manager API Version 8.6 - 10.2
 * qTest Manager API Version 8.6 - 10.2
 *
 * OpenAPI spec version: 8.6 - 10.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.neotys.qtest.api.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * UserGroupResource
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-01-14T16:24:25.829Z")
public class UserGroupResource {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("total_user")
  private Long totalUser = null;

  @SerializedName("is_system")
  private Boolean isSystem = false;

  @SerializedName("is_default")
  private Boolean isDefault = false;

  @SerializedName("authorities")
  private List<AuthorityVM> authorities = null;

  @SerializedName("users")
  private List<UserInfoVM> users = null;

  @SerializedName("user_ids")
  private List<Long> userIds = null;

  @SerializedName("authority_names")
  private List<String> authorityNames = null;

  public UserGroupResource id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public UserGroupResource name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of UserGroup
   * @return name
  **/
  @ApiModelProperty(example = "Name of UserGroup", value = "Name of UserGroup")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UserGroupResource description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of UserGroup
   * @return description
  **/
  @ApiModelProperty(example = "Description of UserGroup", value = "Description of UserGroup")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

   /**
   * The total user of UserGroup
   * @return totalUser
  **/
  @ApiModelProperty(value = "The total user of UserGroup")
  public Long getTotalUser() {
    return totalUser;
  }

   /**
   * Get isSystem
   * @return isSystem
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsSystem() {
    return isSystem;
  }

  public UserGroupResource isDefault(Boolean isDefault) {
    this.isDefault = isDefault;
    return this;
  }

   /**
   * Set this UserGroup as default group for new user
   * @return isDefault
  **/
  @ApiModelProperty(example = "false", value = "Set this UserGroup as default group for new user")
  public Boolean isIsDefault() {
    return isDefault;
  }

  public void setIsDefault(Boolean isDefault) {
    this.isDefault = isDefault;
  }

   /**
   * Get authorities
   * @return authorities
  **/
  @ApiModelProperty(value = "")
  public List<AuthorityVM> getAuthorities() {
    return authorities;
  }

   /**
   * Get users
   * @return users
  **/
  @ApiModelProperty(value = "")
  public List<UserInfoVM> getUsers() {
    return users;
  }

  public UserGroupResource userIds(List<Long> userIds) {
    this.userIds = userIds;
    return this;
  }

  public UserGroupResource addUserIdsItem(Long userIdsItem) {
    if (this.userIds == null) {
      this.userIds = new ArrayList<Long>();
    }
    this.userIds.add(userIdsItem);
    return this;
  }

   /**
   * List of userId will be assign to this group after created
   * @return userIds
  **/
  @ApiModelProperty(value = "List of userId will be assign to this group after created")
  public List<Long> getUserIds() {
    return userIds;
  }

  public void setUserIds(List<Long> userIds) {
    this.userIds = userIds;
  }

  public UserGroupResource authorityNames(List<String> authorityNames) {
    this.authorityNames = authorityNames;
    return this;
  }

  public UserGroupResource addAuthorityNamesItem(String authorityNamesItem) {
    if (this.authorityNames == null) {
      this.authorityNames = new ArrayList<String>();
    }
    this.authorityNames.add(authorityNamesItem);
    return this;
  }

   /**
   * List of authorities for this UserGroup. Values can be: [ ROLE_ADMINCONFIGURATION, ROLE_ADMININFORMATION, ROLE_INSIGHTSEDITOR, ROLE_INSIGHTSEDITOR, ROLE_LAUNCHACCESS, ROLE_PROFILEADMIN, ROLE_PROFILEVIEWER, ROLE_PROJECTARCHIVER, ROLE_PROJECTCREATOR, ROLE_PROJECTUPDATER, ROLE_PROJECTVIEWER, ROLE_PULSEACCESS, ROLE_SITELEVELFIELD, ROLE_USERADMIN, ROLE_USERGROUPMANAGER, ROLE_ANALYTICSVIEWER, ROLE_ANALYTICSDESIGNER, ROLE_ANALYTICSADMIN ]
   * @return authorityNames
  **/
  @ApiModelProperty(value = "List of authorities for this UserGroup. Values can be: [ ROLE_ADMINCONFIGURATION, ROLE_ADMININFORMATION, ROLE_INSIGHTSEDITOR, ROLE_INSIGHTSEDITOR, ROLE_LAUNCHACCESS, ROLE_PROFILEADMIN, ROLE_PROFILEVIEWER, ROLE_PROJECTARCHIVER, ROLE_PROJECTCREATOR, ROLE_PROJECTUPDATER, ROLE_PROJECTVIEWER, ROLE_PULSEACCESS, ROLE_SITELEVELFIELD, ROLE_USERADMIN, ROLE_USERGROUPMANAGER, ROLE_ANALYTICSVIEWER, ROLE_ANALYTICSDESIGNER, ROLE_ANALYTICSADMIN ]")
  public List<String> getAuthorityNames() {
    return authorityNames;
  }

  public void setAuthorityNames(List<String> authorityNames) {
    this.authorityNames = authorityNames;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserGroupResource userGroupResource = (UserGroupResource) o;
    return Objects.equals(this.id, userGroupResource.id) &&
        Objects.equals(this.name, userGroupResource.name) &&
        Objects.equals(this.description, userGroupResource.description) &&
        Objects.equals(this.totalUser, userGroupResource.totalUser) &&
        Objects.equals(this.isSystem, userGroupResource.isSystem) &&
        Objects.equals(this.isDefault, userGroupResource.isDefault) &&
        Objects.equals(this.authorities, userGroupResource.authorities) &&
        Objects.equals(this.users, userGroupResource.users) &&
        Objects.equals(this.userIds, userGroupResource.userIds) &&
        Objects.equals(this.authorityNames, userGroupResource.authorityNames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, totalUser, isSystem, isDefault, authorities, users, userIds, authorityNames);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserGroupResource {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    totalUser: ").append(toIndentedString(totalUser)).append("\n");
    sb.append("    isSystem: ").append(toIndentedString(isSystem)).append("\n");
    sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
    sb.append("    authorities: ").append(toIndentedString(authorities)).append("\n");
    sb.append("    users: ").append(toIndentedString(users)).append("\n");
    sb.append("    userIds: ").append(toIndentedString(userIds)).append("\n");
    sb.append("    authorityNames: ").append(toIndentedString(authorityNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

