/*
 * qTest Manager API Version 8.6 - 10.2
 * qTest Manager API Version 8.6 - 10.2
 *
 * OpenAPI spec version: 8.6 - 10.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.neotys.qtest.api.client.api;

import com.neotys.qtest.api.client.model.ReleaseWithCustomFieldResource;
import com.neotys.qtest.api.client.QtestApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for ReleaseApi
 */
@Ignore
public class ReleaseApiTest {

    private final ReleaseApi api = new ReleaseApi();

    
    /**
     * Creates a Release
     *
     * To create a Release  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 4+
     *
     * @throws QtestApiException
     *          if the Api call fails
     */
    @Test
    public void createTest() throws QtestApiException {
        Long projectId = null;
        ReleaseWithCustomFieldResource body = null;
        ReleaseWithCustomFieldResource response = api.create(projectId, body);

        // TODO: test validations
    }
    
    /**
     * Delete a release
     *
     * To delete a Release
     *
     * @throws QtestApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTest() throws QtestApiException {
        Long projectId = null;
        Long releaseId = null;
        Object response = api.delete(projectId, releaseId);

        // TODO: test validations
    }
    
    /**
     * Gets a Release
     *
     * To retrieve a Release  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 4+
     *
     * @throws QtestApiException
     *          if the Api call fails
     */
    @Test
    public void getTest() throws QtestApiException {
        Long projectId = null;
        Long releaseId = null;
        ReleaseWithCustomFieldResource response = api.get(projectId, releaseId);

        // TODO: test validations
    }
    
    /**
     * Gets multiple Releases
     *
     * To retrieve Releases in a project  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 4+
     *
     * @throws QtestApiException
     *          if the Api call fails
     */
    @Test
    public void getAllTest() throws QtestApiException {
        Long projectId = null;
        Boolean includeClosed = null;
        List<ReleaseWithCustomFieldResource> response = api.getAll(projectId, includeClosed);

        // TODO: test validations
    }
    
    /**
     * Updates a Release
     *
     * To update a Release  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 6+
     *
     * @throws QtestApiException
     *          if the Api call fails
     */
    @Test
    public void updateTest() throws QtestApiException {
        Long projectId = null;
        Long releaseId = null;
        ReleaseWithCustomFieldResource body = null;
        ReleaseWithCustomFieldResource response = api.update(projectId, releaseId, body);

        // TODO: test validations
    }
    
}
