/*
 * qTest Manager API Version 8.6 - 10.2
 * qTest Manager API Version 8.6 - 10.2
 *
 * OpenAPI spec version: 8.6 - 10.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.neotys.qtest.api.client.api;

import com.neotys.qtest.api.client.QtestApiException;
import com.neotys.qtest.api.client.model.AssignedProject;
import com.neotys.qtest.api.client.model.AssignedUsersProject;
import com.neotys.qtest.api.client.model.LoggedUser;
import com.neotys.qtest.api.client.model.Message;
import com.neotys.qtest.api.client.model.OutputStream;
import com.neotys.qtest.api.client.model.ProjectWithUserIdsObject;
import com.neotys.qtest.api.client.model.SearchUserResourceExtensionResponse;
import com.neotys.qtest.api.client.model.SearchUserResponse;
import com.neotys.qtest.api.client.model.UserResource;
import com.neotys.qtest.api.client.model.UserUpdateResource;
import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for UserApi
 */
@Ignore
public class UserApiTest {

    private final UserApi api = new UserApi();

    
    /**
     * Assigns a User to a Project
     *
     * To assign a User to a Project
     *
     * @throws QtestApiException
     *          if the Api call fails
     */
    @Test
    public void assignToProjectTest() throws QtestApiException {
        Long userId = null;
        AssignedProject body = null;
        AssignedProject response = api.assignToProject(userId, body);

        // TODO: test validations
    }
    
    /**
     * Assigns multiple Users to a Project
     *
     * To assign a list of Users to a Project  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 4+
     *
     * @throws QtestApiException
     *          if the Api call fails
     */
    @Test
    public void assignUsersToProjectTest() throws QtestApiException {
        AssignedUsersProject body = null;
        AssignedUsersProject response = api.assignUsersToProject(body);

        // TODO: test validations
    }
    
    /**
     * Invites a User
     *
     * To invite a user to your qTest Manager instance and activate the account. If the password is omitted, the default \&quot;&lt;em&gt;admin123&lt;/em&gt;\&quot; will be used  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 4+
     *
     * @throws QtestApiException
     *          if the Api call fails
     */
    @Test
    public void createUserTest() throws QtestApiException {
        UserResource body = null;
        UserResource response = api.createUser(body);

        // TODO: test validations
    }
    
    /**
     * Queries Users by Username
     *
     * To query for users by their username  &lt;strong&gt;qTest Manager version:&lt;/strong&gt; 8.4.2+
     *
     * @throws QtestApiException
     *          if the Api call fails
     */
    @Test
    public void findByUserNameOrEmailTest() throws QtestApiException {
        String username = null;
        Boolean includeInactiveUsers = null;
        Boolean pagination = null;
        Long page = null;
        Long pageSize = null;
        SearchUserResourceExtensionResponse response = api.findByUserNameOrEmail(username, includeInactiveUsers, pagination, page, pageSize);

        // TODO: test validations
    }
    
    /**
     * Queries Users by Project Name
     *
     * To query for users by names of their assigned projects  - Admin users with &lt;em&gt;Manage Client Users&lt;/em&gt; permission can query users in any projects  - For other users: the API only returns users within projects to which the requesting user is assigned
     *
     * @throws QtestApiException
     *          if the Api call fails
     */
    @Test
    public void findUsersByProjectsNameTest() throws QtestApiException {
        String projectName = null;
        Boolean inactive = null;
        Boolean pagination = null;
        Long page = null;
        Long pageSize = null;
        SearchUserResponse response = api.findUsersByProjectsName(projectName, inactive, pagination, page, pageSize);

        // TODO: test validations
    }
    
    /**
     * Gets a User&#39;s Avatar
     *
     * To retrieve a User&#39;s Avatar
     *
     * @throws QtestApiException
     *          if the Api call fails
     */
    @Test
    public void getAvatarTest() throws QtestApiException {
        Long userId = null;
        OutputStream response = api.getAvatar(userId);

        // TODO: test validations
    }
    
    /**
     * Gets a User
     *
     * To retrieve a User&#39;s information
     *
     * @throws QtestApiException
     *          if the Api call fails
     */
    @Test
    public void getUserByIdTest() throws QtestApiException {
        Long userId = null;
        UserResource response = api.getUserById(userId);

        // TODO: test validations
    }
    
    /**
     * Gets current user&#39;s information
     *
     * To retrieve your information such as username, email, first name, and last name
     *
     * @throws QtestApiException
     *          if the Api call fails
     */
    @Test
    public void reevaluateTokenTest() throws QtestApiException {
        Boolean includeInaccessibleApps = null;
        LoggedUser response = api.reevaluateToken(includeInaccessibleApps);

        // TODO: test validations
    }
    
    /**
     * Remove association between users and projects
     *
     * To remove association between users and projects
     *
     * @throws QtestApiException
     *          if the Api call fails
     */
    @Test
    public void removeAssociationUsersAndProjectsTest() throws QtestApiException {
        List<ProjectWithUserIdsObject> body = null;
        Message response = api.removeAssociationUsersAndProjects(body);

        // TODO: test validations
    }
    
    /**
     * Update user&#39;s information
     *
     * To update information of a user, like : recovery email, password, status...
     *
     * @throws QtestApiException
     *          if the Api call fails
     */
    @Test
    public void updateUserTest() throws QtestApiException {
        Long userId = null;
        UserUpdateResource body = null;
        UserResource response = api.updateUser(userId, body);

        // TODO: test validations
    }
    
}
